import type { Metadata } from "next";
import { Days_One, IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

import { SessionProvider } from "./providers/SessionProvider";
import { AuthProvider } from "./providers/AuthProvider";
import { CartProvider } from "@/context/CartContext";

import { CartDrawer } from "@/components/consumer/cart/CartDrawer";
import { Toaster } from "react-hot-toast";
import { ReactQueryProvider } from "./providers/ReactQueryProvider";

const daysOne = Days_One({
  variable: "--font-days-one",
  subsets: ["latin"],
  weight: "400",
});

// Tipografías del portal de cumplimiento: IBM Plex Sans para la interfaz y
// Plex Mono para los identificadores (documentos, referencias, marcas de
// tiempo), donde importa que los dígitos alineen y las diferencias se vean.
const plexSans = IBM_Plex_Sans({
  variable: "--font-plex-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Ver y Gana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body
        className={`${daysOne.variable} ${plexSans.variable} ${plexMono.variable} font-sans antialiased`}
      >
        <ReactQueryProvider>
        <SessionProvider>
          <AuthProvider>
            <CartProvider>
              {children}
              <CartDrawer />
            </CartProvider>
          </AuthProvider>
        </SessionProvider>
        </ReactQueryProvider>

        {/* 👉 Toaster global */}
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 3000,
            style: {
              background: "#333",
              color: "#fff",
            },
          }}
        />
      </body>
    </html>
  );
}
