import type { Metadata } from "next";
import { Days_One } from "next/font/google";
import "./globals.css";

const daysOne = Days_One({
  variable: "--font-days-one",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${daysOne.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
