import type { Metadata } from "next";
import { Days_One } from "next/font/google";
import { SessionProvider } from './providers/SessionProvider';
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./providers/AuthProvider";
import { ReactQueryProvider } from "./providers/ReactQueryProvider";

const daysOne = Days_One({
  variable: "--font-days-one",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Ver y Gana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${daysOne.variable} font-sans antialiased`}>
        <ReactQueryProvider>
          <SessionProvider>
            <AuthProvider>
              {children}
            </AuthProvider>
          </SessionProvider>
        </ReactQueryProvider>
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 3000,
            style: {
              background: '#333',
              color: '#fff',
            },
          }}
        />
      </body>
    </html>
  );
}

